# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'pipeline_pb'
require 'primitive_pb'
require 'problem_pb'
require 'value_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ScoringConfiguration" do
    optional :method, :enum, 1, "EvaluationMethod"
    optional :folds, :int32, 2
    optional :train_test_ratio, :double, 3
    optional :shuffle, :bool, 4
    optional :random_seed, :int32, 5
    optional :stratified, :bool, 6
  end
  add_message "Score" do
    optional :metric, :message, 1, "ProblemPerformanceMetric"
    optional :fold, :int32, 2
    repeated :targets, :message, 3, "ProblemTarget"
    optional :value, :message, 4, "Value"
  end
  add_message "Progress" do
    optional :state, :enum, 1, "ProgressState"
    optional :status, :string, 2
    optional :start, :message, 3, "google.protobuf.Timestamp"
    optional :end, :message, 4, "google.protobuf.Timestamp"
  end
  add_message "UpdateProblemRequest" do
    optional :search_id, :string, 1
    optional :problem, :message, 2, "ProblemDescription"
  end
  add_message "UpdateProblemResponse" do
  end
  add_message "SearchSolutionsRequest" do
    optional :user_agent, :string, 1
    optional :version, :string, 2
    optional :time_bound, :double, 3
    optional :priority, :double, 4
    repeated :allowed_value_types, :enum, 5, "ValueType"
    optional :problem, :message, 6, "ProblemDescription"
    optional :template, :message, 7, "PipelineDescription"
    repeated :inputs, :message, 8, "Value"
  end
  add_message "SearchSolutionsResponse" do
    optional :search_id, :string, 1
  end
  add_message "EndSearchSolutionsRequest" do
    optional :search_id, :string, 1
  end
  add_message "EndSearchSolutionsResponse" do
  end
  add_message "StopSearchSolutionsRequest" do
    optional :search_id, :string, 1
  end
  add_message "StopSearchSolutionsResponse" do
  end
  add_message "SolutionSearchScore" do
    optional :scoring_configuration, :message, 1, "ScoringConfiguration"
    repeated :scores, :message, 2, "Score"
  end
  add_message "GetSearchSolutionsResultsRequest" do
    optional :search_id, :string, 1
  end
  add_message "GetSearchSolutionsResultsResponse" do
    optional :progress, :message, 1, "Progress"
    optional :done_ticks, :double, 2
    optional :all_ticks, :double, 3
    optional :solution_id, :string, 4
    optional :internal_score, :double, 5
    repeated :scores, :message, 6, "SolutionSearchScore"
  end
  add_message "DescribeSolutionRequest" do
    optional :solution_id, :string, 1
  end
  add_message "PrimitiveStepDescription" do
    map :hyperparams, :string, :message, 1, "Value"
  end
  add_message "SubpipelineStepDescription" do
    repeated :steps, :message, 1, "StepDescription"
  end
  add_message "StepDescription" do
    oneof :step do
      optional :primitive, :message, 1, "PrimitiveStepDescription"
      optional :pipeline, :message, 2, "SubpipelineStepDescription"
    end
  end
  add_message "DescribeSolutionResponse" do
    optional :pipeline, :message, 1, "PipelineDescription"
    repeated :steps, :message, 2, "StepDescription"
  end
  add_message "StepProgress" do
    optional :progress, :message, 1, "Progress"
    repeated :steps, :message, 2, "StepProgress"
  end
  add_message "SolutionRunUser" do
    optional :id, :string, 1
    optional :choosen, :bool, 2
    optional :reason, :string, 3
  end
  add_message "ScoreSolutionRequest" do
    optional :solution_id, :string, 1
    repeated :inputs, :message, 2, "Value"
    repeated :performance_metrics, :message, 3, "ProblemPerformanceMetric"
    repeated :users, :message, 4, "SolutionRunUser"
    optional :configuration, :message, 5, "ScoringConfiguration"
  end
  add_message "ScoreSolutionResponse" do
    optional :request_id, :string, 1
  end
  add_message "GetScoreSolutionResultsRequest" do
    optional :request_id, :string, 1
  end
  add_message "GetScoreSolutionResultsResponse" do
    optional :progress, :message, 1, "Progress"
    repeated :scores, :message, 2, "Score"
  end
  add_message "FitSolutionRequest" do
    optional :solution_id, :string, 1
    repeated :inputs, :message, 2, "Value"
    repeated :expose_outputs, :string, 3
    repeated :expose_value_types, :enum, 4, "ValueType"
    repeated :users, :message, 5, "SolutionRunUser"
  end
  add_message "FitSolutionResponse" do
    optional :request_id, :string, 1
  end
  add_message "GetFitSolutionResultsRequest" do
    optional :request_id, :string, 1
  end
  add_message "GetFitSolutionResultsResponse" do
    optional :progress, :message, 1, "Progress"
    repeated :steps, :message, 2, "StepProgress"
    map :exposed_outputs, :string, :message, 3, "Value"
  end
  add_message "ProduceSolutionRequest" do
    optional :solution_id, :string, 1
    repeated :inputs, :message, 2, "Value"
    repeated :expose_outputs, :string, 3
    repeated :expose_value_types, :enum, 4, "ValueType"
    repeated :users, :message, 5, "SolutionRunUser"
  end
  add_message "ProduceSolutionResponse" do
    optional :request_id, :string, 1
  end
  add_message "GetProduceSolutionResultsRequest" do
    optional :request_id, :string, 1
  end
  add_message "GetProduceSolutionResultsResponse" do
    optional :progress, :message, 1, "Progress"
    repeated :steps, :message, 2, "StepProgress"
    map :exposed_outputs, :string, :message, 3, "Value"
  end
  add_message "SolutionExportRequest" do
    optional :solution_id, :string, 1
    optional :rank, :int32, 2
  end
  add_message "SolutionExportResponse" do
  end
  add_message "ListPrimitivesRequest" do
  end
  add_message "ListPrimitivesResponse" do
    repeated :primitives, :message, 1, "Primitive"
  end
  add_message "HelloRequest" do
  end
  add_message "HelloResponse" do
    optional :user_agent, :string, 1
    optional :version, :string, 2
    repeated :allowed_value_types, :enum, 3, "ValueType"
    repeated :supported_extensions, :string, 4
  end
  add_enum "EvaluationMethod" do
    value :EVALUATION_METHOD_UNDEFINED, 0
    value :HOLDOUT, 1
    value :K_FOLD, 2
    value :LEAVE_ONE_OUT, 100
    value :PREDICTION, 101
    value :TRAINING_DATA, 102
  end
  add_enum "ProgressState" do
    value :PROGRESS_UNKNOWN, 0
    value :PENDING, 1
    value :RUNNING, 2
    value :COMPLETED, 3
    value :ERRORED, 4
  end
end

ScoringConfiguration = Google::Protobuf::DescriptorPool.generated_pool.lookup("ScoringConfiguration").msgclass
Score = Google::Protobuf::DescriptorPool.generated_pool.lookup("Score").msgclass
Progress = Google::Protobuf::DescriptorPool.generated_pool.lookup("Progress").msgclass
UpdateProblemRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateProblemRequest").msgclass
UpdateProblemResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateProblemResponse").msgclass
SearchSolutionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("SearchSolutionsRequest").msgclass
SearchSolutionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("SearchSolutionsResponse").msgclass
EndSearchSolutionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("EndSearchSolutionsRequest").msgclass
EndSearchSolutionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("EndSearchSolutionsResponse").msgclass
StopSearchSolutionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("StopSearchSolutionsRequest").msgclass
StopSearchSolutionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("StopSearchSolutionsResponse").msgclass
SolutionSearchScore = Google::Protobuf::DescriptorPool.generated_pool.lookup("SolutionSearchScore").msgclass
GetSearchSolutionsResultsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSearchSolutionsResultsRequest").msgclass
GetSearchSolutionsResultsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSearchSolutionsResultsResponse").msgclass
DescribeSolutionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("DescribeSolutionRequest").msgclass
PrimitiveStepDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimitiveStepDescription").msgclass
SubpipelineStepDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("SubpipelineStepDescription").msgclass
StepDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("StepDescription").msgclass
DescribeSolutionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("DescribeSolutionResponse").msgclass
StepProgress = Google::Protobuf::DescriptorPool.generated_pool.lookup("StepProgress").msgclass
SolutionRunUser = Google::Protobuf::DescriptorPool.generated_pool.lookup("SolutionRunUser").msgclass
ScoreSolutionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ScoreSolutionRequest").msgclass
ScoreSolutionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ScoreSolutionResponse").msgclass
GetScoreSolutionResultsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetScoreSolutionResultsRequest").msgclass
GetScoreSolutionResultsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetScoreSolutionResultsResponse").msgclass
FitSolutionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("FitSolutionRequest").msgclass
FitSolutionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("FitSolutionResponse").msgclass
GetFitSolutionResultsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetFitSolutionResultsRequest").msgclass
GetFitSolutionResultsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetFitSolutionResultsResponse").msgclass
ProduceSolutionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProduceSolutionRequest").msgclass
ProduceSolutionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProduceSolutionResponse").msgclass
GetProduceSolutionResultsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetProduceSolutionResultsRequest").msgclass
GetProduceSolutionResultsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetProduceSolutionResultsResponse").msgclass
SolutionExportRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("SolutionExportRequest").msgclass
SolutionExportResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("SolutionExportResponse").msgclass
ListPrimitivesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ListPrimitivesRequest").msgclass
ListPrimitivesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ListPrimitivesResponse").msgclass
HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloRequest").msgclass
HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloResponse").msgclass
EvaluationMethod = Google::Protobuf::DescriptorPool.generated_pool.lookup("EvaluationMethod").enummodule
ProgressState = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProgressState").enummodule
