# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'primitive_pb'
require 'value_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ContainerArgument" do
    optional :data, :string, 1
  end
  add_message "DataArgument" do
    optional :data, :string, 1
  end
  add_message "DataArguments" do
    repeated :data, :string, 1
  end
  add_message "PrimitiveArgument" do
    optional :data, :int32, 1
  end
  add_message "PrimitiveArguments" do
    repeated :data, :int32, 1
  end
  add_message "ValueArgument" do
    optional :data, :message, 1, "Value"
  end
  add_message "PrimitiveStepArgument" do
    oneof :argument do
      optional :container, :message, 1, "ContainerArgument"
      optional :data, :message, 2, "DataArgument"
    end
  end
  add_message "PrimitiveStepHyperparameter" do
    oneof :argument do
      optional :container, :message, 1, "ContainerArgument"
      optional :data, :message, 2, "DataArgument"
      optional :primitive, :message, 3, "PrimitiveArgument"
      optional :value, :message, 4, "ValueArgument"
      optional :primitives_set, :message, 5, "PrimitiveArguments"
      optional :data_set, :message, 6, "DataArguments"
    end
  end
  add_message "StepInput" do
    optional :data, :string, 1
  end
  add_message "StepOutput" do
    optional :id, :string, 1
  end
  add_message "PipelineSource" do
    optional :name, :string, 1
    optional :contact, :string, 2
    repeated :pipelines, :string, 3
  end
  add_message "PipelineDescriptionUser" do
    optional :id, :string, 1
    optional :reason, :string, 2
    optional :rationale, :string, 3
  end
  add_message "PipelineDescriptionInput" do
    optional :name, :string, 1
  end
  add_message "PipelineDescriptionOutput" do
    optional :name, :string, 1
    optional :data, :string, 2
  end
  add_message "PrimitivePipelineDescriptionStep" do
    optional :primitive, :message, 1, "Primitive"
    map :arguments, :string, :message, 2, "PrimitiveStepArgument"
    repeated :outputs, :message, 3, "StepOutput"
    map :hyperparams, :string, :message, 4, "PrimitiveStepHyperparameter"
    repeated :users, :message, 5, "PipelineDescriptionUser"
  end
  add_message "SubpipelinePipelineDescriptionStep" do
    optional :pipeline, :message, 1, "PipelineDescription"
    repeated :inputs, :message, 2, "StepInput"
    repeated :outputs, :message, 3, "StepOutput"
  end
  add_message "PlaceholderPipelineDescriptionStep" do
    repeated :inputs, :message, 1, "StepInput"
    repeated :outputs, :message, 2, "StepOutput"
  end
  add_message "PipelineDescriptionStep" do
    oneof :step do
      optional :primitive, :message, 1, "PrimitivePipelineDescriptionStep"
      optional :pipeline, :message, 2, "SubpipelinePipelineDescriptionStep"
      optional :placeholder, :message, 3, "PlaceholderPipelineDescriptionStep"
    end
  end
  add_message "PipelineDescription" do
    optional :id, :string, 1
    optional :source, :message, 2, "PipelineSource"
    optional :created, :message, 3, "google.protobuf.Timestamp"
    optional :context, :enum, 4, "PipelineContext"
    optional :name, :string, 5
    optional :description, :string, 6
    repeated :users, :message, 7, "PipelineDescriptionUser"
    repeated :inputs, :message, 8, "PipelineDescriptionInput"
    repeated :outputs, :message, 9, "PipelineDescriptionOutput"
    repeated :steps, :message, 10, "PipelineDescriptionStep"
  end
  add_enum "PipelineContext" do
    value :PIPELINE_CONTEXT_UNKNOWN, 0
    value :PRETRAINING, 1
    value :TESTING, 2
    value :EVALUATION, 3
    value :PRODUCTION, 4
  end
end

ContainerArgument = Google::Protobuf::DescriptorPool.generated_pool.lookup("ContainerArgument").msgclass
DataArgument = Google::Protobuf::DescriptorPool.generated_pool.lookup("DataArgument").msgclass
DataArguments = Google::Protobuf::DescriptorPool.generated_pool.lookup("DataArguments").msgclass
PrimitiveArgument = Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimitiveArgument").msgclass
PrimitiveArguments = Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimitiveArguments").msgclass
ValueArgument = Google::Protobuf::DescriptorPool.generated_pool.lookup("ValueArgument").msgclass
PrimitiveStepArgument = Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimitiveStepArgument").msgclass
PrimitiveStepHyperparameter = Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimitiveStepHyperparameter").msgclass
StepInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("StepInput").msgclass
StepOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("StepOutput").msgclass
PipelineSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("PipelineSource").msgclass
PipelineDescriptionUser = Google::Protobuf::DescriptorPool.generated_pool.lookup("PipelineDescriptionUser").msgclass
PipelineDescriptionInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("PipelineDescriptionInput").msgclass
PipelineDescriptionOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("PipelineDescriptionOutput").msgclass
PrimitivePipelineDescriptionStep = Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimitivePipelineDescriptionStep").msgclass
SubpipelinePipelineDescriptionStep = Google::Protobuf::DescriptorPool.generated_pool.lookup("SubpipelinePipelineDescriptionStep").msgclass
PlaceholderPipelineDescriptionStep = Google::Protobuf::DescriptorPool.generated_pool.lookup("PlaceholderPipelineDescriptionStep").msgclass
PipelineDescriptionStep = Google::Protobuf::DescriptorPool.generated_pool.lookup("PipelineDescriptionStep").msgclass
PipelineDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("PipelineDescription").msgclass
PipelineContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("PipelineContext").enummodule
