# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Primitive" do
    optional :id, :string, 1
    optional :version, :string, 2
    optional :python_path, :string, 3
    optional :name, :string, 4
    optional :digest, :string, 5
  end
end

Primitive = Google::Protobuf::DescriptorPool.generated_pool.lookup("Primitive").msgclass
