# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: problem.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ProblemPerformanceMetric" do
    optional :metric, :enum, 1, "PerformanceMetric"
    optional :k, :int32, 2
    optional :pos_label, :string, 3
  end
  add_message "Problem" do
    optional :id, :string, 1
    optional :version, :string, 2
    optional :name, :string, 3
    optional :description, :string, 4
    optional :task_type, :enum, 5, "TaskType"
    optional :task_subtype, :enum, 6, "TaskSubtype"
    repeated :performance_metrics, :message, 7, "ProblemPerformanceMetric"
  end
  add_message "ProblemTarget" do
    optional :target_index, :int32, 1
    optional :resource_id, :string, 2
    optional :column_index, :int32, 3
    optional :column_name, :string, 4
  end
  add_message "ProblemInput" do
    optional :dataset_id, :string, 1
    repeated :targets, :message, 2, "ProblemTarget"
  end
  add_message "ProblemDescription" do
    optional :problem, :message, 1, "Problem"
    repeated :inputs, :message, 2, "ProblemInput"
  end
  add_enum "TaskType" do
    value :TASK_TYPE_UNDEFINED, 0
    value :CLASSIFICATION, 1
    value :REGRESSION, 2
    value :CLUSTERING, 3
    value :LINK_PREDICTION, 4
    value :VERTEX_NOMINATION, 5
    value :COMMUNITY_DETECTION, 6
    value :GRAPH_CLUSTERING, 7
    value :GRAPH_MATCHING, 8
    value :TIME_SERIES_FORECASTING, 9
    value :COLLABORATIVE_FILTERING, 10
  end
  add_enum "TaskSubtype" do
    value :TASK_SUBTYPE_UNDEFINED, 0
    value :NONE, 1
    value :BINARY, 2
    value :MULTICLASS, 3
    value :MULTILABEL, 4
    value :UNIVARIATE, 5
    value :MULTIVARIATE, 6
    value :OVERLAPPING, 7
    value :NONOVERLAPPING, 8
  end
  add_enum "PerformanceMetric" do
    value :METRIC_UNDEFINED, 0
    value :ACCURACY, 1
    value :F1, 2
    value :F1_MICRO, 3
    value :F1_MACRO, 4
    value :ROC_AUC, 5
    value :ROC_AUC_MICRO, 6
    value :ROC_AUC_MACRO, 7
    value :MEAN_SQUARED_ERROR, 8
    value :ROOT_MEAN_SQUARED_ERROR, 9
    value :ROOT_MEAN_SQUARED_ERROR_AVG, 10
    value :MEAN_ABSOLUTE_ERROR, 11
    value :R_SQUARED, 12
    value :NORMALIZED_MUTUAL_INFORMATION, 13
    value :JACCARD_SIMILARITY_SCORE, 14
    value :PRECISION_AT_TOP_K, 15
    value :LOSS, 100
  end
end

ProblemPerformanceMetric = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProblemPerformanceMetric").msgclass
Problem = Google::Protobuf::DescriptorPool.generated_pool.lookup("Problem").msgclass
ProblemTarget = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProblemTarget").msgclass
ProblemInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProblemInput").msgclass
ProblemDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProblemDescription").msgclass
TaskType = Google::Protobuf::DescriptorPool.generated_pool.lookup("TaskType").enummodule
TaskSubtype = Google::Protobuf::DescriptorPool.generated_pool.lookup("TaskSubtype").enummodule
PerformanceMetric = Google::Protobuf::DescriptorPool.generated_pool.lookup("PerformanceMetric").enummodule
