# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: value.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ValueError" do
    optional :message, :string, 1
  end
  add_message "Value" do
    oneof :value do
      optional :error, :message, 1, "ValueError"
      optional :double, :double, 2
      optional :int64, :int64, 3
      optional :bool, :bool, 4
      optional :string, :string, 5
      optional :bytes, :bytes, 6
      optional :dataset_uri, :string, 7
      optional :pickle_uri, :string, 8
      optional :pickle_blob, :bytes, 9
      optional :csv_uri, :string, 10
      optional :plasma_id, :bytes, 11
    end
  end
  add_enum "ValueType" do
    value :VALUE_TYPE_UNDEFINED, 0
    value :RAW, 1
    value :DATASET_URI, 2
    value :CSV_URI, 3
    value :PICKLE_URI, 4
    value :PICKLE_BLOB, 5
    value :PLASMA_ID, 6
  end
end

ValueError = Google::Protobuf::DescriptorPool.generated_pool.lookup("ValueError").msgclass
Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("Value").msgclass
ValueType = Google::Protobuf::DescriptorPool.generated_pool.lookup("ValueType").enummodule
